[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

# Must set evm version to paris since solc > 0.8.20 uses op code PUSH0
evm_version = "paris"
optimizer_runs = 100
via_ir = false
revert_strings = "strip"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config